// <auto-generated />
using System;
using Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AnalyzerDbContext))]
    [Migration("20251107020137_Ajuste_AdicionandVeiculoNaOrdem")]
    partial class Ajuste_AdicionandVeiculoNaOrdem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CWOrdemServico", b =>
                {
                    b.Property<int>("nCdOrdemServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdOrdemServico"));

                    b.Property<double>("dVlTotal")
                        .HasColumnType("double precision");

                    b.Property<int>("nCdPrestador")
                        .HasColumnType("integer");

                    b.Property<int>("nCdSeguradora")
                        .HasColumnType("integer");

                    b.Property<int?>("nCdVeiculo")
                        .HasColumnType("integer");

                    b.Property<string>("sDsObservacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sDsOrdem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("tDtOrdem")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("tDtRetorno")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("nCdOrdemServico");

                    b.HasIndex("nCdPrestador");

                    b.HasIndex("nCdSeguradora");

                    b.HasIndex("nCdVeiculo");

                    b.ToTable("OrdemServico");
                });

            modelBuilder.Entity("Domain.Entities.CWOrdemServicoItem", b =>
                {
                    b.Property<int>("nCdItemOrdemServico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdItemOrdemServico"));

                    b.Property<double>("dVlEstimado")
                        .HasColumnType("double precision");

                    b.Property<double>("dVlReal")
                        .HasColumnType("double precision");

                    b.Property<int>("eStatus")
                        .HasColumnType("integer");

                    b.Property<int>("nCdOrdemServico")
                        .HasColumnType("integer");

                    b.Property<int>("nCdPeca")
                        .HasColumnType("integer");

                    b.Property<string>("sDsReparo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdItemOrdemServico");

                    b.HasIndex("nCdOrdemServico");

                    b.HasIndex("nCdPeca");

                    b.ToTable("OrdemServicoItem");
                });

            modelBuilder.Entity("Domain.Entities.CWParceiroNegocio", b =>
                {
                    b.Property<int>("nCdParceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdParceiro"));

                    b.Property<bool>("bFlAtivo")
                        .HasColumnType("boolean");

                    b.Property<int>("eTipo")
                        .HasColumnType("integer");

                    b.Property<string>("sCpfCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmParceiro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sTelefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdParceiro");

                    b.ToTable("PARCEIRO_NEGOCIO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWPecas", b =>
                {
                    b.Property<int>("nCdPeca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdPeca"));

                    b.Property<string>("sCor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sModelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmPeca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("sValor")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("tDtAno")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("nCdPeca");

                    b.ToTable("PECAS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWVeiculo", b =>
                {
                    b.Property<int>("nCdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdVeiculo"));

                    b.Property<string>("sCor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sMecanico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmVeiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sPlaca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("tDtAno")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("nCdVeiculo");

                    b.ToTable("VEICULOS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWOrdemServico", b =>
                {
                    b.HasOne("Domain.Entities.CWParceiroNegocio", "Prestador")
                        .WithMany()
                        .HasForeignKey("nCdPrestador")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CWParceiroNegocio", "Seguradora")
                        .WithMany()
                        .HasForeignKey("nCdSeguradora")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CWVeiculo", "Veiculo")
                        .WithMany()
                        .HasForeignKey("nCdVeiculo");

                    b.Navigation("Prestador");

                    b.Navigation("Seguradora");

                    b.Navigation("Veiculo");
                });

            modelBuilder.Entity("Domain.Entities.CWOrdemServicoItem", b =>
                {
                    b.HasOne("Domain.Entities.CWOrdemServico", "OrdemServico")
                        .WithMany("Itens")
                        .HasForeignKey("nCdOrdemServico")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.CWPecas", "Peca")
                        .WithMany()
                        .HasForeignKey("nCdPeca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrdemServico");

                    b.Navigation("Peca");
                });

            modelBuilder.Entity("Domain.Entities.CWOrdemServico", b =>
                {
                    b.Navigation("Itens");
                });
#pragma warning restore 612, 618
        }
    }
}
