// <auto-generated />
using System;
using Infra.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infra.Migrations
{
    [DbContext(typeof(AnalyzerDbContext))]
    partial class AnalyzerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.CWParceiroNegocio", b =>
                {
                    b.Property<int>("nCdParceiro")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdParceiro"));

                    b.Property<bool>("bFlAtivo")
                        .HasColumnType("boolean");

                    b.Property<int>("eTipo")
                        .HasColumnType("integer");

                    b.Property<string>("sCpfCnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmParceiro")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sTelefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("nCdParceiro");

                    b.ToTable("PARCEIRO_NEGOCIO", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWPecas", b =>
                {
                    b.Property<int>("nCdPeca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdPeca"));

                    b.Property<string>("sCor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sModelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmPeca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("sValor")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("tDtAno")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("nCdPeca");

                    b.ToTable("PECAS", (string)null);
                });

            modelBuilder.Entity("Domain.Entities.CWVeiculo", b =>
                {
                    b.Property<int>("nCdVeiculo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("nCdVeiculo"));

                    b.Property<string>("sCor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sMecanico")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sNmVeiculo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sPlaca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("sTipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("tDtAno")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("nCdVeiculo");

                    b.ToTable("VEICULOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
